### ISSUE TITLE
多进程版本报错

### ISSUE THREAD

**Issue by Lasx** [asdanny/DD#1]
报错

`error----> 'url'
error----> 'url'
error----> 'url'
error----> 'url'
error----> 'url'
error----> 'url'`

divide_url，出了异常。

**Comment by Lasx** [comment]
> PS C:\Users\x\Desktop\DD-main> python .\jdseckillAPI.py
Traceback (most recent call last):
  File "C:\Users\x\Desktop\DD-main\jdseckillAPI.py", line 317, in <module>     
    divide_url, appjmp_set_cookie = JDska.get_appjmp(token_params=token_params)
  File "C:\Users\x\Desktop\DD-main\jdseckillAPI.py", line 172, in get_appjmp   
    appjmp_url = token_params['url']
KeyError: 'url'

**Comment by Lasx** [comment]
修改为固定sign后报错
